hiddenimports = ['keyring.credentials',
                 'keyring.backends.file',
                 'keyring.backends.Gnome',
                 'keyring.backends.Google',
                 'keyring.backends.keyczar',
                 'keyring.backends.kwallet',
                 'keyring.backends.multi',
                 'keyring.backends.OS_X',
                 'keyring.backends.pyfs',
                 'keyring.backends.SecretService',
                 'keyring.backends.Windows',
                 'keyring.util',
                 'keyring.util.escape',
                 'keyring.util.XDG',
                 'keyring.util.platform_',
                 'keyring.util.properties']
